#!/usr/bin/env bash

# install homebrew
if ! type "brew" > /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# verify lastest homebrew
brew update

# upgrade any already installed formulae
brew upgrade

# install useful binaries
brew install git
brew install erlang
brew install postgresql

# install deployment tools
brew install awscli
brew install heroku

# casks
brew cask install spectacle 
brew cask install slack
brew cask install 1password
brew cask install postico
brew cask install visual-studio-code
brew cask install google-chrome
brew cask install notion
brew cask install dash

# remove outdated versions from the cellar
brew cleanup