#!/usr/bin/env bash

set -e
echo ''

DOTFILES_ROOT="${HOME}/.dotfiles"
DOTFILES_REPO="git@github.com:elizabethmv/dotfiles.git"

if [[ ! -d ${DOTFILES_ROOT} ]]; then
  git clone ${DOTFILES_REPO} ${DOTFILES_ROOT}
fi

cd ${DOTFILES_ROOT}

info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

link_file () {
  local src=$1 dst=$2

  ln -sf "$src" "$dst"
  success "linked $src to $dst"
}

DOTFILES_HOME=$(pwd)/home

install_dotfiles () {
  info "installing dotfiles"

  for src in $(find "$DOTFILES_HOME"/* -maxdepth 2 -name '*')
  do
    dst="$HOME/.$(basename "${src}")"
    link_file "$src" "$dst"
  done
}

install_dotfiles
echo ''
success "successfully installed dotfiles"